server:
  port: 7070

spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kkb_mm?serverTime=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

logging:
  file:
    name: mm_wx_api.log
    path: ./
  level:
    root: debug
    com.kkb.mapper: debug
  pattern:
    console: log-%level %msg%n

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
